### ISSUE TITLE
Not compatible with numpy 1.18.0

### ISSUE THREAD

**Issue by philipperemy** [MhLiao/DB#87]
```
  File "/home/premy/projects/DB/venv/lib/python3.6/site-packages/imgaug/random.py", line 851, in _normalize_generator_np117_
    elif isinstance(generator, np.random.bit_generator.BitGenerator):
AttributeError: module 'numpy.random' has no attribute 'bit_generator'
```

Works with 1.16.2.

**Comment by Yangxx12138** [comment]
I encountered the same problem and solved it by changing the version of numpy

**Comment by wuzuowuyou** [comment]
numpy 1.17.4

**Comment by nicolasmetallo** [comment]
You can also fix this by adding at the beginning of your code (e.g. demo.py)

```
import numpy
numpy.random.bit_generator = numpy.random._bit_generator
```
